name: flutter_speed_ui_app
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'   #ใส่ป้องกัน จัดระเบียบโค๊ต(Ctrl+Ship+F)แล้ว ลงมาบรรทัดเดียวกัน 


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1  #ใส่ google font
  font_awesome_flutter: ^10.8.0  #ใส่ font awesome

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0


flutter:

  
  uses-material-design: true
  assets:
    - assets/images/   
    #จะดึงรูป จากที่ไหนก็ต้องนำมาใส่ ดึงจาก floder assets    sub floder images


  

  
